export enum ErrorCode {
  ERR_UNAUTHORIZED = 'ERR_UNAUTHORIZED',
  ERR_BAD_EVENT_SCHEMA = 'ERR_BAD_EVENT_SCHEMA',
  ERR_UNSUPPORTED_AUDIO_FORMAT = 'ERR_UNSUPPORTED_AUDIO_FORMAT',
  ERR_PROVIDER_STT_UNAVAILABLE = 'ERR_PROVIDER_STT_UNAVAILABLE',
  ERR_PROVIDER_TTS_UNAVAILABLE = 'ERR_PROVIDER_TTS_UNAVAILABLE',
  ERR_LLM_UNAVAILABLE = 'ERR_LLM_UNAVAILABLE',
  ERR_SESSION_STATE = 'ERR_SESSION_STATE',
  ERR_RATE_LIMIT = 'ERR_RATE_LIMIT',
}
